fruits = ("apple", "banana", "cherry", "mango", "banana")
print(len(fruits))
print(fruits[1])
sunil=list(fruits)
sunil[2]="grapes"
print(sunil)
thistuple = ("apple", "banana", "cherry", "mango", "banana")
y = list(thistuple)
y.append("orange")
thistuple = tuple(y)
print(thistuple)